version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/src/app 
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}